### PR TITLE
add random speed tile generation in pbf flavor

### PR DESCRIPTION
**Pull request by kevinkreiser**
related to #48 

---

note: this program imports the flatbuffer modules but it doesnt actually do anything with flatbuffers that is a `todo` for @kdiluca and @dgearhart

anyway this makes pbf files witih speed information similar to the original json we were working towards. i reworked the notion of the time period covered by the tile to make more since (imho). ive also remove the ids themselves from the tile and just put in the tile level and index and then made the segments sequential (which is good because they are sorted this way in osmlr and in flatbuffers). it also reduces the size of the files. 

there are a couple of things we may be able to do to make the file size smaller. since protobuf uses varint we could possible switch the variances to use this so long as we keep the absolute value of them small, this would require math when using the value client side but could make the files smaller. we could also measure average speed as the difference from reference speed also we'd have the problem of negative numbers so maybe we couldnt make that work...

take a look at the speedtile proto definition and see if it meets our needs. its split up in 2 ways to make it so we can store just the right amount of data without getting fancy with geographic partitioning. the first way its split up is by a top level object called `Tile` which only holds an array of `SubTile`s. in this way any number of `Tile`s in different files can just be concatenated to get all the data in one place if desired. what this allows (as described in #48) is splitting up the segment index space (defaults to 10k per subtile) so that a client only has a portion of all ids at any one time but with some simple math can know what subtile will hold a given segment index should they need it. 

the second way the tiles are broken up is at the `SubTile` level where its basically again two arrays, one of `Entry`s and another of `NextSegment`s where we can store one or the other or both or none in a given `SubTile`. This lets us easily separate the `NextSegment` entries from the regular speed entries if we want to so that client applications can treat that info as optional.

The program in this pr lets you configure all of the above via arguments.

When all is said and done the largest tile, which is the level 2 tokyo tile (so large it cant be created using the json methodology as its well over a gig of json) comes down to the following:

```console
./make_speeds.py --output-prefix 415.spd --separate-next-segments-prefix 415.nex --osmlr ../../size_test/159.osmlr blah
getting osmlr segments
simulating 1 week of speeds at hourly intervals for 107973 segments
creating new subtile starting at 0
Removing 415.spd.0
writing subtile to 415.spd.0
wrote subtile to 415.spd.0
Removing 415.nex.0
writing subtile to 415.nex.0
wrote subtile to 415.nex.0
creating new subtile starting at 10000
Removing 415.spd.1
writing subtile to 415.spd.1
wrote subtile to 415.spd.1
Removing 415.nex.1
writing subtile to 415.nex.1
wrote subtile to 415.nex.1
creating new subtile starting at 20000
Removing 415.spd.2
writing subtile to 415.spd.2
wrote subtile to 415.spd.2
Removing 415.nex.2
writing subtile to 415.nex.2
wrote subtile to 415.nex.2
creating new subtile starting at 30000
Removing 415.spd.3
writing subtile to 415.spd.3
wrote subtile to 415.spd.3
Removing 415.nex.3
writing subtile to 415.nex.3
wrote subtile to 415.nex.3
creating new subtile starting at 40000
Removing 415.spd.4
writing subtile to 415.spd.4
wrote subtile to 415.spd.4
Removing 415.nex.4
writing subtile to 415.nex.4
wrote subtile to 415.nex.4
creating new subtile starting at 50000
Removing 415.spd.5
writing subtile to 415.spd.5
wrote subtile to 415.spd.5
Removing 415.nex.5
writing subtile to 415.nex.5
wrote subtile to 415.nex.5
creating new subtile starting at 60000
Removing 415.spd.6
writing subtile to 415.spd.6
wrote subtile to 415.spd.6
Removing 415.nex.6
writing subtile to 415.nex.6
wrote subtile to 415.nex.6
creating new subtile starting at 70000
Removing 415.spd.7
writing subtile to 415.spd.7
wrote subtile to 415.spd.7
Removing 415.nex.7
writing subtile to 415.nex.7
wrote subtile to 415.nex.7
creating new subtile starting at 80000
Removing 415.spd.8
writing subtile to 415.spd.8
wrote subtile to 415.spd.8
Removing 415.nex.8
writing subtile to 415.nex.8
wrote subtile to 415.nex.8
creating new subtile starting at 90000
Removing 415.spd.9
writing subtile to 415.spd.9
wrote subtile to 415.spd.9
Removing 415.nex.9
writing subtile to 415.nex.9
wrote subtile to 415.nex.9
creating new subtile starting at 100000
Removing 415.spd.10
writing subtile to 415.spd.10
wrote subtile to 415.spd.10
Removing 415.nex.10
writing subtile to 415.nex.10
wrote subtile to 415.nex.10
done
```
some uncompressed sizes:
```console
foo:bar$ ls -hal --sort time *nex* *spd*
-rw-r--r-- 1 kkreiser kkreiser 47M Aug  8 09:52 415.nex.10
-rw-r--r-- 1 kkreiser kkreiser 20M Aug  8 09:52 415.spd.10
-rw-r--r-- 1 kkreiser kkreiser 59M Aug  8 09:51 415.nex.9
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:50 415.spd.9
-rw-r--r-- 1 kkreiser kkreiser 59M Aug  8 09:49 415.nex.8
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:48 415.spd.8
-rw-r--r-- 1 kkreiser kkreiser 59M Aug  8 09:47 415.nex.7
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:46 415.spd.7
-rw-r--r-- 1 kkreiser kkreiser 59M Aug  8 09:45 415.nex.6
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:44 415.spd.6
-rw-r--r-- 1 kkreiser kkreiser 59M Aug  8 09:43 415.nex.5
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:42 415.spd.5
-rw-r--r-- 1 kkreiser kkreiser 59M Aug  8 09:41 415.nex.4
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:40 415.spd.4
-rw-r--r-- 1 kkreiser kkreiser 59M Aug  8 09:39 415.nex.3
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:38 415.spd.3
-rw-r--r-- 1 kkreiser kkreiser 59M Aug  8 09:37 415.nex.2
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:36 415.spd.2
-rw-r--r-- 1 kkreiser kkreiser 60M Aug  8 09:35 415.nex.1
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:34 415.spd.1
-rw-r--r-- 1 kkreiser kkreiser 59M Aug  8 09:33 415.nex.0
-rw-r--r-- 1 kkreiser kkreiser 25M Aug  8 09:33 415.spd.0
```

some compressed sizes:

```console
foo:bar$ ls -hal --sort time *nex* *spd*
-rw-r--r-- 1 kkreiser kkreiser  23M Aug  8 09:52 415.nex.10.gz
-rw-r--r-- 1 kkreiser kkreiser 9.0M Aug  8 09:52 415.spd.10.gz
-rw-r--r-- 1 kkreiser kkreiser  29M Aug  8 09:51 415.nex.9.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:50 415.spd.9.gz
-rw-r--r-- 1 kkreiser kkreiser  29M Aug  8 09:49 415.nex.8.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:48 415.spd.8.gz
-rw-r--r-- 1 kkreiser kkreiser  29M Aug  8 09:47 415.nex.7.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:46 415.spd.7.gz
-rw-r--r-- 1 kkreiser kkreiser  29M Aug  8 09:45 415.nex.6.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:44 415.spd.6.gz
-rw-r--r-- 1 kkreiser kkreiser  29M Aug  8 09:43 415.nex.5.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:42 415.spd.5.gz
-rw-r--r-- 1 kkreiser kkreiser  29M Aug  8 09:41 415.nex.4.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:40 415.spd.4.gz
-rw-r--r-- 1 kkreiser kkreiser  29M Aug  8 09:39 415.nex.3.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:38 415.spd.3.gz
-rw-r--r-- 1 kkreiser kkreiser  29M Aug  8 09:37 415.nex.2.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:36 415.spd.2.gz
-rw-r--r-- 1 kkreiser kkreiser  30M Aug  8 09:35 415.nex.1.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:34 415.spd.1.gz
-rw-r--r-- 1 kkreiser kkreiser  29M Aug  8 09:33 415.nex.0.gz
-rw-r--r-- 1 kkreiser kkreiser  12M Aug  8 09:33 415.spd.0.gz
```

above you'll see `spd` files and `nex` files as well as numerical suffixes. this is because i've chosen for this run to split the tiles in both ways mentioned above, where subtiles are different files (numerical suffixes) and where speed data is separated from next segment data (spd vs nex file names).

### CODE REVIEW

**Comment by dgearhart** [comment]
:ship:

**Comment by yeesian** [comment]
Are these speed tiles currently being served anywhere? May I have a sample to create a client for fetching them?

**Comment by kevinkreiser** [comment]
@yeesian they werent at the time my colleagues and i left the project. perhaps @kpwebb or @Holly-Transport might be able to assist you there.

**Comment by yeesian** [comment]
Oh I think development might be happening in https://github.com/sharedstreets/sharedstreets-ref-system. Thanks!

**Comment by kpwebb** [comment]
@yeesian just found this thread! This project has migrated to SharedStreets as you noticed, and we've started hosting a global tiles using the new SharedStreets format. You can find more info about the hosted tiles here:

https://github.com/sharedstreets/sharedstreets-ref-system/issues/15

**Pull request merged**
